### ISSUE TITLE
incorrect output

### ISSUE THREAD

**Issue by Jayaramhack** [GanapriyaS/Student-Record-Management#2]
the entering subjects are printed in same line and next input stings are do this like in same line plz...............say something :)
![Screenshot (46)](https://user-images.githubusercontent.com/86995970/145708515-ad80b654-b9cb-4363-a170-1d3f6e8eb235.png)

**Comment by GanapriyaS** [comment]
Please do changes as mentioned in the previous issue and rerun the code. I hope it solves the issue :)
